apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: app1-ns
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
